In [107]:
import numpy as np
import matplotlib.pyplot as plt


In [108]:
arr = np.arange(12).reshape(3, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [109]:
padded_arr = np.pad(arr, ((1, 1), (1, 1)), mode='edge')
print(padded_arr)

[[ 0  0  1  2  3  3]
 [ 0  0  1  2  3  3]
 [ 4  4  5  6  7  7]
 [ 8  8  9 10 11 11]
 [ 8  8  9 10 11 11]]


In [ ]:
def averaging(arr, kernel):
  kH, kW = kernel.shape
  
  averaged = arr.copy().astype(float)
  print(f"Copy to store averages\n{averaged}\n")
  
  padded_arr = np.pad(arr, ((kH // 2, kH // 2), (kW // 2, kW // 2)), mode='edge')
  print(f"Padded Array\n{padded_arr}\n")
  
  windows = []
  for i in range(arr.shape[0] - kH + 1):
    for j in range(arr.shape[1] - kW + 1):
      window = np.array(padded_arr[i:i+kH, j:j+kW])
      windows.append(window)
      avg = np.mean(window)
      # center_i = i + kH // 2
      # center_j = j + kW // 2
      # averaged[center_i, center_j] = avg  
      averaged[i, j] = avg    
    
  return averaged, windows



arr = np.arange(24).reshape(6, 4)
print(f"Original\n{arr}\n")

kernel = np.ones((3, 3))

smoothed, windows = averaging(arr, kernel)
print(f"Smoothed Array\n{smoothed}")

Original
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Copy to store averages
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]

Padded Array
[[ 0  0  1  2  3  3]
 [ 0  0  1  2  3  3]
 [ 4  4  5  6  7  7]
 [ 8  8  9 10 11 11]
 [12 12 13 14 15 15]
 [16 16 17 18 19 19]
 [20 20 21 22 23 23]
 [20 20 21 22 23 23]]

Smoothed Array
[[ 2.33333333  1.          2.          3.        ]
 [ 4.          5.          6.          7.        ]
 [ 8.          9.          9.         11.        ]
 [12.         13.         14.         13.        ]
 [16.         17.         18.         19.        ]
 [20.         21.         22.         23.        ]]


In [111]:
for window in windows:
  print(f"{window}, {np.mean(window)})")

[[0 0 1]
 [0 0 1]
 [4 4 5]], 1.6666666666666667)
[[0 1 2]
 [0 1 2]
 [4 5 6]], 2.3333333333333335)
[[0 0 1]
 [4 4 5]
 [8 8 9]], 4.333333333333333)
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]], 5.0)
[[ 4  4  5]
 [ 8  8  9]
 [12 12 13]], 8.333333333333334)
[[ 4  5  6]
 [ 8  9 10]
 [12 13 14]], 9.0)
[[ 8  8  9]
 [12 12 13]
 [16 16 17]], 12.333333333333334)
[[ 8  9 10]
 [12 13 14]
 [16 17 18]], 13.0)
