In [1]:
import numpy as np

arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#1. First two columns from all rows
arr[:, 0:2]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [3]:
#2. last two rows and last two columns
arr[1:, 2:4]

array([[ 7,  8],
       [11, 12]])

In [4]:
#3. middle 4 numbers
arr[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [5]:
#4 every second column from all rows
arr[:, 1:2]

array([[ 2],
       [ 6],
       [10]])

In [6]:
#5 reverse the rows
arr[::-1, :]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [7]:
#6 get diagonal elements
# arr[:, ]
np.diag(arr)

array([ 1,  6, 11])

In [8]:
diag_ele = [arr[i, i] for i in range(min(arr.shape))]
print(diag_ele)
print(arr[0, 0])

[np.int64(1), np.int64(6), np.int64(11)]
1


In [9]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
#second row all columns
print(a3[1])
print(a3[1:2])
# print(type(a3[1:2]))
print(a3[1::2])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [11]:
#second and third 2d arrays of a3
print(a3[1:3])
#first and third 2d arrays of a3
print(a3[::2])

[[[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [12]:
#second row of first 2d array of a3
print(a3[0, 1])
print(a3[0,1,:])

[3 4 5]
[3 4 5]


In [13]:
#second column of second 2d array of a3
print(a3[1, :, 1])
print(a3[1, :, 1:2])

[10 13 16]
[[10]
 [13]
 [16]]


In [14]:
# second to thrid row and second to third column of third matrix of a3
print(a3[2, 1:, 1:])

[[22 23]
 [25 26]]


In [15]:
# print(a3[::3, ::3, ::3])
print(a3[::2, 0, ::2])

[[ 0  2]
 [18 20]]
