In [1]:
import numpy as np

In [2]:
arr = np.arange(24).reshape(6, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [4]:
# First three columns from all rows
print(arr[:, 0:3])

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]
 [20 21 22]]


In [6]:
# First three columns from first three rows
print(arr[:3, 0:3])

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
